### ISSUE TITLE
Launch experiments

### ISSUE THREAD

**Issue by elias-ramzi** [yash0307/RecallatK_surrogate#3]
Hi,
Thanks for the repo !

I want to reproduce the results of your paper. I see that in `main.py` you have some hyper-parameters setup depending on the dataset. So in order to reproduce your results (eg on iNaturalist) I just need to run:
```
python main.py ----dataset Inaturalist
```
There is no need for other hyper-parameters ?

Do you know how much time each each run take ?

Thanks !

**Comment by yash0307** [comment]
Please take a look at the updated readme. Let me know if there are any additional concerns. Closing for now.

**Comment by elias-ramzi** [comment]
Thanks, I will look into it!
